# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import file_pb2 as file__pb2
import metadata_pb2 as metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayload.proto\x12\tse.umu.cs\x1a\nfile.proto\x1a\x0emetadata.proto\"X\n\nNeoPayload\x12 \n\x04\x66ile\x18\x01 \x01(\x0b\x32\x12.se.umu.cs.NeoFile\x12(\n\x08metadata\x18\x02 \x01(\x0b\x32\x16.se.umu.cs.NeoMetadataB \n\tse.umu.csB\x11NeoPayloadMessageP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tse.umu.csB\021NeoPayloadMessageP\001'
  _globals['_NEOPAYLOAD']._serialized_start=56
  _globals['_NEOPAYLOAD']._serialized_end=144
# @@protoc_insertion_point(module_scope)
