volumes:
  persistence: True

zookeeper:
  volumes:
    data:
      size: 100Mi
  resources:
    requests:
      cpu: "0.2"
      memory: "128Mi"
    limits:
      memory: "1Gi"
      cpu: "1"
bookkeeper:
  volumes:
    journal:
      size: 100Mi
    ledgers:
      size: 100Mi
  resources:
    requests:
      cpu: "0.2"
      memory: "128Mi"
    limits:
      memory: "1Gi"
      cpu: "1"
broker:
  resources:
    requests:
      cpu: "0.2"
      memory: "128Mi"
    limits:
      memory: "1Gi"
      cpu: "1"
proxy:
  resources:
    requests:
      cpu: "0.2"
      memory: "128Mi"
    limits:
      memory: "512Mi"
      cpu: "1"
autorecovery:
  resources:
    requests:
      cpu: "0.2"
      memory: "128Mi"
    limits:
      memory: "1Gi"
      cpu: "1"
functionsWorker:
  replicas: 1
  runtime: kubernetes
  config:
    logLevel: "OFF"  # Disable logging
    numFunctionPackageReplicas: 1
    functionInstanceMaxResources:
      disk: 10000000000
      ram: 500000000
      cpu: 0.3
  resources:
    requests:
      cpu: "0.3"

kube-prometheus-stack:
  enabled: true
  prometheus:
    prometheusSpec:
      remoteWrite:
        - url: "https://prometheus-prod-39-prod-eu-north-0.grafana.net/api/prom/push"
          basicAuth:
              username:
                name: kubepromsecret
                key: username
              password:
                name: kubepromsecret
                key: password

