apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: chaos-middleware-schedule
  namespace: chaos-mesh
spec:
  schedule: "@every 30s"
  type: PodChaos
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - middleware
      labelSelectors:
        "bb": "middleware"
