apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pulsar-scaler
  namespace: converter
spec:
  scaleTargetRef:
    name: converter
  pollingInterval: 20
  triggers:
  - type: pulsar
    metadata:
      adminURL: http://10.43.28.107:90
      topic: persistent://public/inout/input-topic
      isPartitionedTopic: "false"
      subscription: input-subscription 
      msgBacklogThreshold: '3'
  cooldownPeriod: 100
  maxReplicaCount: 8
  minReplicaCount: 1
