apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pulsar-scaler
  namespace: converter
spec:
  scaleTargetRef:
    name: converter
  pollingInterval: 30
  triggers:
  - type: pulsar
    metadata:
      adminURL: http://10.43.101.106:80
      topic: persistent://public/inout/input-topic
      isPartitionedTopic: "false"
      subscription: keda-scaler
      msgBacklogThreshold: '5'
  cooldownPeriod: 100
  maxReplicaCount: 20
